function graphMe(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 26-Sep-2019 09:02:08

% Create figure
figure1 = figure('NumberTitle','off','Name','Time vs Points');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','1');
set(plot1(2),'DisplayName','2');
set(plot1(3),'DisplayName','3');
set(plot1(4),'DisplayName','4');
set(plot1(5),'DisplayName','5');
set(plot1(6),'DisplayName','6');
set(plot1(7),'DisplayName','7');
set(plot1(8),'DisplayName','8');
set(plot1(9),'DisplayName','9');
set(plot1(10),'DisplayName','10');

% Create ylabel
ylabel('Computational Time(s)','Interpreter','none');

% Create xlabel
xlabel('Number of Points [10^(3+x)]','Interpreter','none');

% Create title
title('Time vs Points');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XTick',[0 2 4]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','northwest');
title(legend1,'Dimentions');
saveas(gcf,'for.png');
