function graphMe5(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 26-Sep-2019 13:33:08

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','10');

% Create ylabel
ylabel({'Time(s)'});

% Create xlabel
xlabel('Number of Points [10^(3+x)]','Interpreter','none');

% Create title
title({'Time vs Points (dist)'});

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XTick',[0 2 4]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','northwest');
title(legend1,'Dimetions');
saveas(gcf,'dist.png');
