#!/bin/bash
#PBS -A loni_cyen405
#PBS -l walltime=01:00:00
#PBS -l nodes=1:ppn=20
#PBS -N Lab2-Q2 
#PBS -o q2.out
#PBS -e q2.err
#PBS -q workq

work="/home/mhe016/lab2"
MPIFILE="q2"
cd $work
echo "run with 4 threads\n"
mpirun -machinefile $PBS_NODEFILE -np 4 ./$MPIFILE
echo "\nrun with 8 threads\n"
mpirun -machinefile $PBS_NODEFILE -np 8 ./$MPIFILE
